#!/usr/bin/env python3
"""Re-score logged recommendation calls against the latest bhavcopy close.

Reads data/call_tracker.csv (the calls I have made, with the price at the time),
fetches the current exchange close via the same bhavcopy path the portfolio page
uses, and rewrites the auto-generated scorecard block at the bottom of
docs/CALL_POSTMORTEM.md. Pure Python, no LLM — cheap to run on a schedule.

CSV columns: symbol,call_date,call_type,ref_price,ref_label,target,stop,note
  symbol     exchange ticker (RAYMOND.NS / KELTECH.BO)
  ref_price  the price at the time of the call (blank if unknown)
  target/stop optional levels; a crossing gets flagged
"""
import csv
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from daily_portfolio_telegram import build_price_map, last_trading_bhav  # noqa: E402

TRACKER = REPO / "data" / "call_tracker.csv"
DOC = REPO / "docs" / "CALL_POSTMORTEM.md"
MARK = "<!-- AUTO-SCORECARD -->"


def cmp_for(symbol, prices):
    base = symbol.split(".")[0]
    px = prices.get(symbol) or prices.get(base + ".NS") or prices.get(base + ".BO")
    return round(px[0], 2) if px else None


def flag(row, cmp_):
    """Return a short note when price crossed a target or stop."""
    out = []
    for level, name in ((row.get("target"), "target"), (row.get("stop"), "stop")):
        if level and cmp_ is not None:
            try:
                lv = float(level)
            except ValueError:
                continue
            if name == "target" and cmp_ >= lv:
                out.append(f"target ₹{lv:g} hit")
            if name == "stop" and cmp_ <= lv:
                out.append(f"stop ₹{lv:g} hit")
    return "; ".join(out)


def main():
    trade_date, nse, bse = last_trading_bhav()
    prices = build_price_map(nse, bse)
    rows = list(csv.DictReader(open(TRACKER)))

    lines = [
        MARK,
        f"\n## Auto-scorecard (bhavcopy close {trade_date})\n",
        "Regenerated by `scripts/update_call_tracker.py`. Edit the calls in "
        "`data/call_tracker.csv`, not this block.\n",
        "| Symbol | Call | Date | Ref ₹ | Now ₹ | Move | Flag | Note |",
        "|---|---|---|---:|---:|---:|---|---|",
    ]
    for r in rows:
        sym = r["symbol"]
        cmp_ = cmp_for(sym, prices)
        ref = r.get("ref_price", "").strip()
        move = ""
        if ref and cmp_ is not None:
            try:
                move = f"{(cmp_ / float(ref) - 1) * 100:+.0f}%"
            except (ValueError, ZeroDivisionError):
                move = ""
        cmp_s = f"{cmp_:,.2f}" if cmp_ is not None else "—"
        ref_s = f"{float(ref):,.2f}" if ref else "—"
        lines.append(
            f"| {sym} | {r['call_type']} | {r['call_date']} | {ref_s} | "
            f"{cmp_s} | {move} | {flag(r, cmp_)} | {r.get('note','')} |"
        )

    block = "\n".join(lines) + "\n"
    text = DOC.read_text()
    if MARK in text:
        text = text[: text.index(MARK)].rstrip() + "\n\n" + block
    else:
        text = text.rstrip() + "\n\n---\n\n" + block
    DOC.write_text(text)
    print(f"call tracker updated: {len(rows)} calls, close {trade_date}")


if __name__ == "__main__":
    main()
